plugins {
    id 'fabric-loom' version '1.2-SNAPSHOT'
    id 'maven-publish'
}

repositories {
    mavenCentral()
    maven {
        name = 'Fabric'
        url = 'https://maven.fabricmc.net/'
    }
}

version = '1.0.0'

minecraft {
    mappings '1.20.4+build.1'
    loaderVersion '0.14.22'
    modId 'donutflipscannermod'
}

dependencies {
    minecraft 'com.mojang:minecraft:1.20.4'
    mappings 'net.fabricmc:yarn:1.20.4+build.1:v2'
    modImplementation 'net.fabricmc:fabric-loader:0.14.22'
    modImplementation 'net.fabricmc.fabric-api:fabric-api:0.89.0+1.20.4'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

processResources {
    inputs.property 'version', project.version
    from(sourceSets.main.resources.srcDirs) {
        include 'fabric.mod.json'
        expand [project: project]
    }
    into 'build/resources/main'
}
